version: '2.0'
parameter_level: method
label: Scenario2
deployment_type: mobile
measurement_scale: component
is_follow_up: False
reporting_delay: 2
consider_daylight: True
max_workday: 10
weather_envs:
  precip: [0.0, 0.5]
  temp: [-20.0, 40.0]
  wind: [0.0, 3.5]  
n_crews: 5
sensor: 
  type: OGI_camera_rk
  MDL: [0.01275, 2.78e-6]
  QE: 2.2
cost:
  per_site: 500
coverage:
  spatial: 0.8
  temporal: 0.8
t_bw_sites: 
  vals: [30]
time: 120